### ISSUE TITLE
[TO-DO] ENHANCEMENT / FIXES / REFACTOR / DOCS / CI

### ISSUE THREAD

**Issue by pixincreate** [pixincreate/PixeneOS#12]
- [x] #65
- [x] Refactor afsr setup once upstream is updated
- [x] Safe checks
  - [x] Add documentation in code
  - [x] Make code more robust and safe
  - [x] Make functions independent such that they can be used separately if needed
  - [x] Make modules configurable
- [x] CI/CD pipeline
  - [x] Setup Bot (renovate?) for updating dependencies
  - [x] GitHub pages for deployments
  - [x] Add uploader service to release pipeline
  - [x] Make update channel configurable
  - [x] Clean up and make it reusable. 
  	- Current implementation works perfectly only in ideal environments
  	- For re-usability, viz., another build of same version with root support or build with updated magisk version seems to be buggy at present
  	- [x] #66
- [x] Refactor
  - [x] https://github.com/pixincreate/PixeneOS/issues/8
  - [x] https://github.com/pixincreate/PixeneOS/issues/9
  - [x] Add logging (#349)
- [x] ~Integrate `BCR` in default `dialer` by patching with `my-avbroot-setup`~ superseded by native automatic call recording in the GrapheneOS Dialer ([2026090500](https://grapheneos.org/releases#2026090500))
- [x] Make `patch_ota` respect the module toggles (#349)
- [x] Make `declarations.sh` generic (#349)
  - [x] Move user specific variables out of `declarations.sh` to `env.toml` (#349)
- [x] Possibly make this project a template
